### ISSUE TITLE
Month not defined

### ISSUE THREAD

**Issue by AriaFantom** [sebg0/DiscordModBot#1]
(node:44236) UnhandledPromiseRejectionWarning: ReferenceError: month is not defined
    at module.exports.run (/home/ubuntu/Youva-Bot/src/Commands/Moderation/Warn.js:52:15)
    at module.exports.run (/home/ubuntu/Youva-Bot/src/Events/message/message.js:106:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)

![image](https://user-images.githubusercontent.com/55119711/116933371-18194500-ac81-11eb-9b4a-c65a0ae0a344.png)

**Comment by sebg0** [comment]
All instances of this error should now be fixed. If there's any other issues let me know. Thanks!
